FROM golang:1.22.0-alpine3.18

WORKDIR /app

COPY /micro-service/batch-service /app

RUN go mod tidy && \
    go install github.com/cosmtrek/air@v1.46.0 &&  \
    go install github.com/volatiletech/sqlboiler/v4@latest && \
    go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-mysql@latest && \
    go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

EXPOSE 3010

CMD ["air", "-c", ".air.toml"]