FROM --platform=linux/amd64 node:20-alpine
RUN npm i -g @nestjs/cli

WORKDIR /app

COPY /gateway/backend-for-frontend /app

RUN npm install --frozen-lockfile

EXPOSE 3000

CMD ["npm", "run", "start:dev"]