// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	Accounts           string
	SchemaMigrations   string
	Sessions           string
	Users              string
	VerificationTokens string
}{
	Accounts:           "accounts",
	SchemaMigrations:   "schema_migrations",
	Sessions:           "sessions",
	Users:              "users",
	VerificationTokens: "verification_tokens",
}
