FROM golang:1.22.0-alpine3.18

RUN apk update && apk add git

WORKDIR /app

COPY /micro-service/user-service /app

RUN go mod tidy && \
    go install github.com/cosmtrek/air@v1.46.0

CMD ["air", "-c", ".air.toml"]