import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { Header } from "@/components/layout/Header";
import { Providers } from "./provider";
import { cn } from "@/lib/utils";
import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(fontSans.variable)}>
        <Providers>
          <Header />
          <div className="w-screen h-24" />
          {children}
        </Providers>
      </body>
    </html>
  );
}
