name: BE_USER_SERVICE_CI

on:
  push:
    branches: 
      - "main"
      - "develop"
      - "feature/*"
    paths:
      - "micro-service/user-service/**"
      - ".github/workflows/ci_be_user_service.yml"
#
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: ['1.22']

    defaults:
      run:
        working-directory: ./micro-service/user-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
          cache: true
          cache-dependency-path: go.sum

      - name: Go Lint
        uses: golangci/golangci-lint-action@v4
        with:
            version: v1.54

      - name: Go Build
        run: go build -v ./...


