name: BE_USER_SERVICE_CI

on:
  push:
    branches: 
      - "main"
      - "develop"
      - "feature/*"
    paths:
      - "micro-service/user-service/**"
      - ".github/workflows/ci_be_user_service.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: ['1.22']

    defaults:
      run:
        working-directory: ./micro-service/user-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: false

    #   - name: Install dependencies
    #     run: go mod download
            #  go install go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2

      - name: go pwd
        run: pwd

      - name: Go Lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2 && make lint
        # uses: reviewdog/action-golangci-lint@v2
        # with:
        #     github_token: ${{ secrets.GITHUB_TOKEN }}
        #     go_version: ${{ matrix.go }}
        #     reporter: github-pr-review
        #     level: warning
        #     # version: latest
        #     working-directory: ./micro-service/user-service/
        #     golangci_lint_flags: "--config=.golangci.yml"

      - name: Go Build
        run: go build -v ./...


